version: 0.2

phases:
  pre_build:
    commands:
      - echo Building a Zippied Folder fo the Respoitory...
      # - yum install wget unzip
      # - wget https://releases.hashicorp.com/terraform/1.0.6/terraform_1.0.6_linux_amd64.zip
      # - unzip ./terraform_1.0.6_linux_amd64.zip -d /usr/local/bin
      # - terraform -v

  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR/
      - pwd
      #- export AWS_ACCESS_KEY_ID= $AWS_KEY_ID
      #- export AWS_SECRET_ACCESS_KEY= $AWS_SECRET_KEY
      #- export TF_LOG= DEBUG
      #- echo $AWS_ACCEESS_KEY_ID
      #- echo $AWS_SECRET_ACCESS_KEY
      #- aws s3 ls
      # - terraform init
      # - terraform $TF_COMMAND

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    #- '**/nonprod/*'
    - '**/*'
  #base-directory: -  udemy-tf-git/MyArtifact.zip
