version: 0.2

phases:
  pre_build:
    commands:
      - echo Building a Zippied Folder fo the Respoitory...
      # - yum install wget unzip
      # - wget https://releases.hashicorp.com/terraform/1.0.6/terraform_1.0.6_linux_amd64.zip
      # - unzip ./terraform_1.0.6_linux_amd64.zip -d /usr/local/bin
      # - terraform -v

  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR/
      - pwd

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    #- '**/nonprod/*'
    - '**/*'
  #base-directory: -  udemy-tf-git/MyArtifact.zip
