-
  name: 'Install prerequisites fo learning app'
  hosts: slave1
  become: yes
  gather_facts: yes
  tasks:
  - name: Install a list of packages
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - httpd
      - mariadb
      - mariadb-server
      - firewalld
      - php
      - php-mysql
      - git

  - name: Start and Enable services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - httpd
      - mariadb
      - firewalld

  - name: Add rules to firewalld
    become: yes
    command: firewall-cmd --permanent --zone=public --add-port={{ item }}/tcp
    loop:
      - 3306
      - 80
  - name: Create a new database with name 'ecomdb'
    mysql_db:
      name: ecomdb
      state: present

  - name: Create database user with name 'ecomuser' and password with all database privileges
    mysql_user:
      name: ecomuser
      password: ecompassword
      priv: '*.*:ALL'
      state: present

  # Copy database dump file to remote host and restore it to database 'my_db'
  - name: Copy database dump file
    copy:
      src: /home/ansible/learning-app-ecommerce/ansible/db-load-script.sql
      dest: /tmp
  - name: Restore database
    mysql_db:
      name: ecomdb
      state: import
      target: /tmp/db-load-script.sql

  - name: Reload Firewalld
    become: yes
    command: firewall-cmd --reload
  - name: Update httpd conf with index.php
    become: yes
    command: "{{ item }}"
    with_items:
      - sed -i 's/index.html/index.php/g' /etc/httpd/conf/httpd.conf
      - service httpd restart
      - sudo rm -rf /var/www/html
      - sudo mkdir /var/www/html
      - git clone https://github.com/Bhavishya101/learning-app-ecommerce.git /var/www/html/
      - sed -i 's/172.20.1.101/localhost/g' /var/www/html/index.php

  # - name: Replace a entry in index.php file
  #   lineinfile:
  #     path: /var/www/html/index.php
  #     regexp: '172.20.1.101'
  #     line: 172.20.1.101

  # - name: Replace a entry in index.php file
  #   replace:
  #     dest: /var/www/html/index.php
  #     regexp: '(172.20.1.101)'
  #     replace: '//  172.20.1.101' ##
